### ISSUE TITLE
Import Error: No module named clearbit

### ISSUE THREAD

**Issue by Maves12** [bhavsec/reconspider#14]
After installation, starting reconspider returns:

Traceback (most recent call last):
  File "reconspider.py", line 1, in <module>
    from main import argparse
  File "/root/Documents/recon/reconspider/main/__init__.py", line 1, in <module>
    from .args import *
  File "/root/Documents/recon/reconspider/main/args.py", line 1, in <module>
    from modules import ipEnum, domEnum, domWhois, comDetail, fetchData, socket
  File "/root/Documents/recon/reconspider/modules/__init__.py", line 1, in <module>
    from .company import *
  File "/root/Documents/recon/reconspider/modules/company.py", line 2, in <module>
    import requests, json, clearbit, os    
ImportError: No module named clearbit

Any ideas?

I am on Kali Linux.

**Comment by bhavsec** [comment]
This happened bcoz pip3 in your system was not installed. 

This issue is now fixed, please download new version of the tool using git clone and install using this command: python3 install.py

If the same error returns, please reply to this issue with output.
