### ISSUE TITLE
Error while using URL

### ISSUE THREAD

**Issue by Thomas0921** [bhavsec/reconspider#18]
**Describe the bug**
`Reconspider >> 2
URL >> https://github.com
Traceback (most recent call last):
  File "reconspider.py", line 32, in <module>
    from core import repl_prompt
  File "D:\reconspider\core\__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "D:\reconspider\core\repl_prompt.py", line 91, in <module>
    repl()
  File "D:\reconspider\core\repl_prompt.py", line 41, in repl
    url = socket.gethostbyname(url_inp)  # URL to IP address conversion
socket.gaierror: [Errno 11001] getaddrinfo failed`

**To Reproduce**
1. Searching URL

**Expected behavior**
URL data will be shown below

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [Window 10, Chrome 75]

**Comment by Aravindha1234u** [comment]
Do Check the New Version
