### ISSUE TITLE
Still error on phonenumber option

### ISSUE THREAD

**Issue by srkadia** [bhavsec/reconspider#30]
Still showing this error...

please fix this asap,

Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/home/srk/Tools/Osint/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/home/srk/Tools/Osint/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/home/srk/Tools/Osint/reconspider/core/repl_prompt.py", line 64, in repl
    Phonenumber(ph)
  File "/home/srk/Tools/Osint/reconspider/plugins/Phonenumber.py", line 17, in Phonenumber
    print("Number: "+get['number'])
KeyError: 'number'

**Comment by Aravindha1234u** [comment]
Did you pull from repository after new commit?

**Comment by Anonymous-srk** [comment]
Yes, infact I reinstalled it

**Comment by Aravindha1234u** [comment]
Let me check it I guess push isn't successful. Will update you on this

**Comment by Aravindha1234u** [comment]
We have fixed this issue and a new commit has been done. Pull it from the repository or run an updated and check again if you face again issue. Please do let us know

https://github.com/bhavsec/reconspider/commit/e9f76844d75eee6f27630df1d90b8ea622d7f671
