### ISSUE TITLE
Find facebook information with ID doesn't work

### ISSUE THREAD

**Issue by anupam19** [bhavsec/reconspider#33]
Log:
``` Reconspider >> 11

1.Facebook 
2.Twitter 
3.Instagram

Username >> IamSRK        
choice >> 1
Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/$LOCATION/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/$LOCATION/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/$LOCATION/reconspider/core/repl_prompt.py", line 121, in repl
    user(choice,username)
  File "/$LOCATION/reconspider/plugins/Username.py", line 76, in user
    find_name()
  File "/$LOCATION/reconspider/plugins/Username.py", line 34, in find_name
    name = main_div.find(id="fb-timeline-cover-name").get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by MetadataCleaner** [comment]
After specifying username and Facebook as choice, it returns the message "Profile not found"

**Comment by carlvanman** [comment]
i also have an issue here, after i search a name (this is for the 3 options) the program just close with no message
