### ISSUE TITLE
MAC address info NOT WORKING

### ISSUE THREAD

**Issue by Anonymoushacker4926** [bhavsec/reconspider#36]
MAC ADDRESS LOOKUP (Eg:08:00:69:02:01:FC) >> D2:C3:00:00:00:00

Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/root/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/root/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/root/reconspider/core/repl_prompt.py", line 99, in repl
    MacAddressLookup(mac)
  File "/root/reconspider/plugins/macaddress.py", line 6, in MacAddressLookup
    result=response.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

OS: Linux (parrot)
Browser: firefox (default)
version: latest for everything

**Comment by acheong08** [comment]
Same issue here

**Comment by AjanSharma** [comment]
1) Go to the folder where you have clone reconspider
2) Go to plugins folder
3) open macaddress.py in any text editor
4) Comment out everything and paste the below code (It will solve the issue)

import requests



def MacAddressLookup(mac):

    print(mac)

    url = ("https://macvendors.co/api/" + mac)

    response=requests.get(url)

    result=response.json()

    final = result['result']

    for x,y in final.items():

         print(x,"   -     ",y)

**Comment by mikeaden2007** [comment]
Reconpider is just trash

**Comment by Anonymoushacker4926** [comment]
Nothing works on it, use my tool I'm making right now. It's way better. & actually works

**Comment by pycoder74** [comment]
Check to see if the api is returning anything
