### ISSUE TITLE
twitter information dosen't work

### ISSUE THREAD

**Issue by shanow7** [bhavsec/reconspider#38]
Reconspider >> 11                                                                                                                                                    

1.Facebook 
2.Twitter 
3.Instagram

Username >> tsurugi_linux
choice >> 2
User Name --> Not Found'NoneType' object has no attribute 'text'

User Id --> Not Found'NoneType' object has no attribute 'text'

Decription not provided by the user'NoneType' object has no attribute 'text'

Location not provided by the user'NoneType' object has no attribute 'text'

No contact link is provided by the user'NoneType' object has no attribute 'a'

The joined date is not provided by the user'NoneType' object has no attribute 'text'

Birth Date not provided by the user'NoneType' object has no attribute 'span'

Total Tweets --> Zerolist index out of range

Following --> Zerolist index out of range

Followers --> Zerolist index out of range

Likes send by him --> Zerolist index out of range

Traceback (most recent call last):
  File "/home/osint/reconspider/plugins/Username.py", line 192, in ScrapTweets
    if span_box[4].text != "More ":
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/home/osint/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/home/osint/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/home/osint/reconspider/core/repl_prompt.py", line 121, in repl
    user(choice,username)
  File "/home/osint/reconspider/plugins/Username.py", line 10, in user
    ScrapTweets(username)
  File "/home/osint/reconspider/plugins/Username.py", line 197, in ScrapTweets
    print("No. of parties he is Subscribed to --> Zero" + + str(e))
TypeError: bad operand type for unary +: 'str'

**Comment by bhavsec** [comment]
This Issue has been fixed by @IshanBatish.
