### ISSUE TITLE
I dosen't know what is this but after installation of reconspider it is saying me this 

### ISSUE THREAD

**Issue by Sarthak232121** [bhavsec/reconspider#41]
/data/data/com.termux/files/usr/lib/python3.9/site-packages/Pillow-8.0.1-py3.9-linux-armv7l.egg/PIL/Image.py:115: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: None
Pillow version: 8.0.1
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/reconspider/reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/data/data/com.termux/files/home/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/data/data/com.termux/files/home/reconspider/core/repl_prompt.py", line 11, in <module>
    from plugins.metadata import gps_analyzer
  File "/data/data/com.termux/files/home/reconspider/plugins/metadata.py", line 2, in <module>
    from PIL import Image
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Pillow-8.0.1-py3.9-linux-armv7l.egg/PIL/Image.py", line 97, in <module>
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: None
Pillow version: 8.0.1

**Comment by radarhere** [comment]
What version of setuptools are you using? This is a known problem starting with 49.1.3, so I would suggest upgrading to at least 49.3.2.

**Comment by bhavsec** [comment]
ReconSpider is not fully compatible with Termux, Please try to run it on Linux machine for better results. Make sure you are using Python 3 and follow the installation procedure via **setup.py** from **README.md**.
