### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by christiandgv** [bhavsec/reconspider#45]
any option chosen generates errors, for example option 9

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6eddbaa4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.ipstack.com', port=80): Max retries exceeded with url: /104.238.58.62?access_key=276cfee2c31729505691e515e8321a02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eddbaa4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/f3n1x/PROJECTS/reconspider/reconspider.py", line 39, in <module>
    from core import repl_prompt
  File "/home/f3n1x/PROJECTS/reconspider/core/__init__.py", line 1, in <module>
    from .repl_prompt import *
  File "/home/f3n1x/PROJECTS/reconspider/core/repl_prompt.py", line 153, in <module>
    repl()
  File "/home/f3n1x/PROJECTS/reconspider/core/repl_prompt.py", line 104, in repl
    IPHeatmap()
  File "/home/f3n1x/PROJECTS/reconspider/plugins/ipaddress.py", line 26, in IPHeatmap
    read_single_IP(IP)
  File "/home/f3n1x/PROJECTS/reconspider/plugins/ipaddress.py", line 40, in read_single_IP
    r = requests.get("http://api.IPstack.com/" + IP + "?access_key=" + api_key)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.ipstack.com', port=80): Max retries exceeded with url: /104.238.58.62?access_key=276cfee2c31729505691e515e8321a02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eddbaa4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by bhavsec** [comment]
Make sure you are using Python 3 and follow the installation procedure via **setup.py** from README.md.
